// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace StealthBot.SpecFlow.Modules
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Safespots")]
    [NUnit.Framework.CategoryAttribute("Safespots")]
    public partial class SafespotsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "Safespots"};
        
#line 1 "Safespots.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Modules", "Safespots", "In order to intelligently flee to safety\r\nAs the bot\r\nI want to determine if I sh" +
                    "ould flee and where to go", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 7
#line hidden
            TechTalk.SpecFlow.Table table35 = new TechTalk.SpecFlow.Table(new string[] {
                        "!this",
                        "TypeID",
                        "Type",
                        "GroupID",
                        "Group"});
            table35.AddRow(new string[] {
                        "<<cloak>>",
                        "11370",
                        "Prototype Cloaking Device I",
                        "330",
                        "Cloaking Device"});
#line 8
testRunner.Given("Items exist", ((string)(null)), table35, "Given ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Am I safe - In Station")]
        public void AmISafe_InStation()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Am I safe - In Station", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 12
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 13
testRunner.Given("I am in a station", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 14
testRunner.When("I check if I am safe", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 15
testRunner.Then("the result should be \'true\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Am I safe - In space, within tower shields of any tower")]
        public void AmISafe_InSpaceWithinTowerShieldsOfAnyTower()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Am I safe - In space, within tower shields of any tower", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 17
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 18
testRunner.Given("I am in space", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table36 = new TechTalk.SpecFlow.Table(new string[] {
                            "Name",
                            "X",
                            "Y",
                            "Z",
                            "TypeID",
                            "Distance",
                            "GroupID"});
                table36.AddRow(new string[] {
                            "Cylons Were Here",
                            "1",
                            "1",
                            "1",
                            "27786",
                            "29999",
                            "365"});
#line 19
testRunner.And("I have entities", ((string)(null)), table36, "And ");
#line hidden
                TechTalk.SpecFlow.Table table37 = new TechTalk.SpecFlow.Table(new string[] {
                            "TypeID",
                            "Type",
                            "ShieldRadius"});
                table37.AddRow(new string[] {
                            "27786",
                            "True Sansha Control Tower",
                            "30000"});
#line 23
testRunner.And("I have item info", ((string)(null)), table37, "And ");
#line hidden
#line 26
testRunner.When("I check if I am safe", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 27
testRunner.Then("the result should be \'true\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Am I safe - In Space, within warp range of a \"safe\" bookmark, local is safe")]
        public void AmISafe_InSpaceWithinWarpRangeOfASafeBookmarkLocalIsSafe()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Am I safe - In Space, within warp range of a \"safe\" bookmark, local is safe", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 29
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 30
testRunner.Given("I am in space", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 31
testRunner.And("I am in solarsystem ID \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 32
testRunner.And("my safe bookmark prefix is \'safe: \'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table38 = new TechTalk.SpecFlow.Table(new string[] {
                            "Label",
                            "X",
                            "Y",
                            "Z",
                            "SolarSystemID"});
                table38.AddRow(new string[] {
                            "safe: bookmark",
                            "0",
                            "0",
                            "0",
                            "1"});
#line 33
testRunner.And("I have bookmarks", ((string)(null)), table38, "And ");
#line hidden
#line 37
testRunner.And("I am at point \'0\',\'0\',\'0\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 38
testRunner.And("local is safe", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 39
testRunner.When("I check if I am safe", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 40
testRunner.Then("the result should be \'true\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Am I safe - In Space, within warp range of a \"safe\" bookmark, local is not safe b" +
            "ut I have a cloak and can cloak")]
        public void AmISafe_InSpaceWithinWarpRangeOfASafeBookmarkLocalIsNotSafeButIHaveACloakAndCanCloak()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Am I safe - In Space, within warp range of a \"safe\" bookmark, local is not safe b" +
                    "ut I have a cloak and can cloak", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 42
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 43
testRunner.Given("I am in space", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 44
testRunner.And("I am in solarsystem ID \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 45
testRunner.And("my safe bookmark prefix is \'safe: \'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table39 = new TechTalk.SpecFlow.Table(new string[] {
                            "Label",
                            "X",
                            "Y",
                            "Z",
                            "SolarSystemID"});
                table39.AddRow(new string[] {
                            "safe: bookmark",
                            "0",
                            "0",
                            "0",
                            "1"});
#line 46
testRunner.And("I have bookmarks", ((string)(null)), table39, "And ");
#line hidden
#line 50
testRunner.And("I am at point \'0\',\'0\',\'0\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 51
testRunner.And("local is not safe", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table40 = new TechTalk.SpecFlow.Table(new string[] {
                            "ID",
                            "ToItem"});
                table40.AddRow(new string[] {
                            "00000001",
                            "<<cloak>>"});
#line 52
testRunner.And("I have cloaking device modules", ((string)(null)), table40, "And ");
#line hidden
                TechTalk.SpecFlow.Table table41 = new TechTalk.SpecFlow.Table(new string[] {
                            "ID",
                            "IsTargetingMe"});
#line 55
testRunner.And("I have entities", ((string)(null)), table41, "And ");
#line hidden
#line 57
testRunner.When("I check if I am safe", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 58
testRunner.Then("the result should be \'true\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Am I safe - In Space, within warp range of a \"safe\" bookmark, local is not safe b" +
            "ut I have a cloak and can\'t cloak")]
        public void AmISafe_InSpaceWithinWarpRangeOfASafeBookmarkLocalIsNotSafeButIHaveACloakAndCantCloak()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Am I safe - In Space, within warp range of a \"safe\" bookmark, local is not safe b" +
                    "ut I have a cloak and can\'t cloak", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 60
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 61
testRunner.Given("I am in space", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 62
testRunner.And("I am in solarsystem ID \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 63
testRunner.And("my safe bookmark prefix is \'safe: \'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table42 = new TechTalk.SpecFlow.Table(new string[] {
                            "ID",
                            "Name",
                            "X",
                            "Y",
                            "Z",
                            "GroupID",
                            "Distance",
                            "IsTargetingMe"});
                table42.AddRow(new string[] {
                            "1",
                            "Joe Jackass",
                            "0",
                            "0",
                            "0",
                            "444",
                            "150000",
                            "true"});
#line 64
testRunner.And("I have entities", ((string)(null)), table42, "And ");
#line hidden
                TechTalk.SpecFlow.Table table43 = new TechTalk.SpecFlow.Table(new string[] {
                            "Label",
                            "X",
                            "Y",
                            "Z",
                            "SolarSystemID"});
                table43.AddRow(new string[] {
                            "safe: bookmark",
                            "0",
                            "0",
                            "0",
                            "1"});
#line 67
testRunner.And("I have bookmarks", ((string)(null)), table43, "And ");
#line hidden
#line 71
testRunner.And("I am at point \'0\',\'0\',\'0\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 72
testRunner.And("local is not safe", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table44 = new TechTalk.SpecFlow.Table(new string[] {
                            "ID",
                            "ToItem"});
                table44.AddRow(new string[] {
                            "00000001",
                            "<<cloak>>"});
#line 73
testRunner.And("I have cloaking device modules", ((string)(null)), table44, "And ");
#line hidden
#line 76
testRunner.When("I check if I am safe", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 77
testRunner.Then("the result should be \'false\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Am I safe - In Space, within warp range of a \"safe\" bookmark, bookmark in differe" +
            "nt system")]
        public void AmISafe_InSpaceWithinWarpRangeOfASafeBookmarkBookmarkInDifferentSystem()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Am I safe - In Space, within warp range of a \"safe\" bookmark, bookmark in differe" +
                    "nt system", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 79
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 80
testRunner.Given("I am in space", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 81
testRunner.And("I am in solarsystem ID \'0\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 82
testRunner.And("my safe bookmark prefix is \'safe: \'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table45 = new TechTalk.SpecFlow.Table(new string[] {
                            "Label",
                            "X",
                            "Y",
                            "Z",
                            "SolarSystemID"});
                table45.AddRow(new string[] {
                            "safe: bookmark",
                            "0",
                            "0",
                            "0",
                            "1"});
#line 83
testRunner.And("I have bookmarks", ((string)(null)), table45, "And ");
#line hidden
#line 87
testRunner.And("I am at point \'0\',\'0\',\'0\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 88
testRunner.When("I check if I am safe", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 89
testRunner.Then("the result should be \'false\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Am I safe - In space, no \"safe\" bookmarks, within warp-in range of a planet, loca" +
            "l is safe")]
        public void AmISafe_InSpaceNoSafeBookmarksWithinWarp_InRangeOfAPlanetLocalIsSafe()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Am I safe - In space, no \"safe\" bookmarks, within warp-in range of a planet, loca" +
                    "l is safe", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 91
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 92
testRunner.Given("I am in space", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table46 = new TechTalk.SpecFlow.Table(new string[] {
                            "ID",
                            "Name",
                            "X",
                            "Y",
                            "Z",
                            "GroupID",
                            "Distance"});
                table46.AddRow(new string[] {
                            "1",
                            "Dodixie IX",
                            "0",
                            "0",
                            "0",
                            "7",
                            "100000000000"});
#line 94
testRunner.And("I have entities", ((string)(null)), table46, "And ");
#line hidden
#line 98
testRunner.And("my safe bookmark prefix is \'safe: \'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table47 = new TechTalk.SpecFlow.Table(new string[] {
                            "Label",
                            "X",
                            "Y",
                            "Z",
                            "SolarSystemID"});
#line 99
testRunner.And("I have bookmarks", ((string)(null)), table47, "And ");
#line hidden
#line 101
testRunner.And("local is safe", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 102
testRunner.When("I check if I am safe", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 103
testRunner.Then("the result should be \'true\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Am I safe - In space, no \"safe\" bookmarks, within warp-in range of a planet, loca" +
            "l is not safe but I have a cloak and can cloak")]
        public void AmISafe_InSpaceNoSafeBookmarksWithinWarp_InRangeOfAPlanetLocalIsNotSafeButIHaveACloakAndCanCloak()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Am I safe - In space, no \"safe\" bookmarks, within warp-in range of a planet, loca" +
                    "l is not safe but I have a cloak and can cloak", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 105
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 106
testRunner.Given("I am in space", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table48 = new TechTalk.SpecFlow.Table(new string[] {
                            "ID",
                            "Name",
                            "X",
                            "Y",
                            "Z",
                            "GroupID",
                            "Distance",
                            "IsTargetingMe"});
                table48.AddRow(new string[] {
                            "1",
                            "Dodixie IX",
                            "0",
                            "0",
                            "0",
                            "7",
                            "100000000000",
                            "false"});
#line 108
testRunner.And("I have entities", ((string)(null)), table48, "And ");
#line hidden
#line 112
testRunner.And("my safe bookmark prefix is \'safe: \'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table49 = new TechTalk.SpecFlow.Table(new string[] {
                            "Label",
                            "X",
                            "Y",
                            "Z",
                            "SolarSystemID"});
#line 113
testRunner.And("I have bookmarks", ((string)(null)), table49, "And ");
#line hidden
#line 115
testRunner.And("local is not safe", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table50 = new TechTalk.SpecFlow.Table(new string[] {
                            "ID",
                            "ToItem"});
                table50.AddRow(new string[] {
                            "00000001",
                            "<<cloak>>"});
#line 116
testRunner.And("I have cloaking device modules", ((string)(null)), table50, "And ");
#line hidden
#line 119
testRunner.When("I check if I am safe", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 120
testRunner.Then("the result should be \'true\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Am I safe - In space, no \"safe\" bookmarks, within warp-in range of a planet, loca" +
            "l is not safe but I have a cloak and can\'t cloak")]
        public void AmISafe_InSpaceNoSafeBookmarksWithinWarp_InRangeOfAPlanetLocalIsNotSafeButIHaveACloakAndCantCloak()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Am I safe - In space, no \"safe\" bookmarks, within warp-in range of a planet, loca" +
                    "l is not safe but I have a cloak and can\'t cloak", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 122
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 123
testRunner.Given("I am in space", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table51 = new TechTalk.SpecFlow.Table(new string[] {
                            "ID",
                            "Name",
                            "X",
                            "Y",
                            "Z",
                            "GroupID",
                            "Distance",
                            "IsTargetingMe"});
                table51.AddRow(new string[] {
                            "1",
                            "Dodixie IX",
                            "0",
                            "0",
                            "0",
                            "7",
                            "100000000000",
                            "false"});
                table51.AddRow(new string[] {
                            "2",
                            "Joe Jackass",
                            "0",
                            "0",
                            "0",
                            "444",
                            "150000",
                            "true"});
#line 125
testRunner.And("I have entities", ((string)(null)), table51, "And ");
#line hidden
#line 130
testRunner.And("my safe bookmark prefix is \'safe: \'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table52 = new TechTalk.SpecFlow.Table(new string[] {
                            "Label",
                            "X",
                            "Y",
                            "Z",
                            "SolarSystemID"});
#line 131
testRunner.And("I have bookmarks", ((string)(null)), table52, "And ");
#line hidden
#line 133
testRunner.And("local is not safe", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table53 = new TechTalk.SpecFlow.Table(new string[] {
                            "ID",
                            "ToItem"});
                table53.AddRow(new string[] {
                            "00000001",
                            "<<cloak>>"});
#line 134
testRunner.And("I have cloaking device modules", ((string)(null)), table53, "And ");
#line hidden
#line 137
testRunner.When("I check if I am safe", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 138
testRunner.Then("the result should be \'false\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Am I safe - Negative test - If we\'re not explicitly at a safespot, we shouldn\'t b" +
            "e considered at one")]
        public void AmISafe_NegativeTest_IfWereNotExplicitlyAtASafespotWeShouldntBeConsideredAtOne()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Am I safe - Negative test - If we\'re not explicitly at a safespot, we shouldn\'t b" +
                    "e considered at one", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 140
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 141
testRunner.Given("I am in space", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 142
testRunner.And("my safe bookmark prefix is \'safe: \'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table54 = new TechTalk.SpecFlow.Table(new string[] {
                            "Label",
                            "X",
                            "Y",
                            "Z",
                            "SolarSystemID"});
#line 143
testRunner.And("I have bookmarks", ((string)(null)), table54, "And ");
#line hidden
#line 145
testRunner.When("I check if I am safe", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 146
testRunner.Then("the result should be \'false\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Am I safe - In space, safe bookmarks, within warp-in range of a planet")]
        public void AmISafe_InSpaceSafeBookmarksWithinWarp_InRangeOfAPlanet()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Am I safe - In space, safe bookmarks, within warp-in range of a planet", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 148
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 149
testRunner.Given("I am in space", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table55 = new TechTalk.SpecFlow.Table(new string[] {
                            "ID",
                            "Name",
                            "X",
                            "Y",
                            "Z",
                            "GroupID",
                            "Distance",
                            "IsTargetingMe"});
                table55.AddRow(new string[] {
                            "1",
                            "Dodixie IX",
                            "0",
                            "0",
                            "0",
                            "7",
                            "100000000000",
                            "false"});
#line 151
testRunner.And("I have entities", ((string)(null)), table55, "And ");
#line hidden
#line 155
testRunner.And("I am at point \'0\',\'0\',\'0\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 156
testRunner.And("I am in solarsystem ID \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 157
testRunner.And("my safe bookmark prefix is \'safe: \'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 158
testRunner.And("local is safe", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table56 = new TechTalk.SpecFlow.Table(new string[] {
                            "Label",
                            "X",
                            "Y",
                            "Z",
                            "SolarSystemID"});
                table56.AddRow(new string[] {
                            "safe: bookmark",
                            "146546",
                            "-64343684",
                            "4646",
                            "1"});
#line 159
testRunner.And("I have bookmarks", ((string)(null)), table56, "And ");
#line hidden
#line 162
testRunner.When("I check if I am safe", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 163
testRunner.Then("the result should be \'false\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Am I safe - In space, no safe bookmarks, stations present, within warp-in range o" +
            "f a planet")]
        public void AmISafe_InSpaceNoSafeBookmarksStationsPresentWithinWarp_InRangeOfAPlanet()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Am I safe - In space, no safe bookmarks, stations present, within warp-in range o" +
                    "f a planet", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 165
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 166
testRunner.Given("I am in space", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table57 = new TechTalk.SpecFlow.Table(new string[] {
                            "ID",
                            "Name",
                            "X",
                            "Y",
                            "Z",
                            "GroupID",
                            "Distance",
                            "IsTargetingMe"});
                table57.AddRow(new string[] {
                            "1",
                            "Dodixie IX",
                            "0",
                            "0",
                            "0",
                            "7",
                            "100000000000",
                            "false"});
                table57.AddRow(new string[] {
                            "2",
                            "Dodixie IX - 9 - Astral Mining Inc. Refinery",
                            "100",
                            "100",
                            "100",
                            "15",
                            "750987",
                            "false"});
#line 168
testRunner.And("I have entities", ((string)(null)), table57, "And ");
#line hidden
#line 173
testRunner.And("I am at point \'0\',\'0\',\'0\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 174
testRunner.And("I am in solarsystem ID \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 175
testRunner.And("my safe bookmark prefix is \'safe: \'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 176
testRunner.And("local is safe", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table58 = new TechTalk.SpecFlow.Table(new string[] {
                            "Label",
                            "X",
                            "Y",
                            "Z",
                            "SolarSystemID"});
#line 177
testRunner.And("I have bookmarks", ((string)(null)), table58, "And ");
#line hidden
#line 179
testRunner.When("I check if I am safe", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 180
testRunner.Then("the result should be \'false\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Get safespot - All options available, should pick space safe")]
        public void GetSafespot_AllOptionsAvailableShouldPickSpaceSafe()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get safespot - All options available, should pick space safe", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 182
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 183
testRunner.Given("I am in space", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 184
testRunner.And("my safe bookmark prefix is \'safe: \'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table59 = new TechTalk.SpecFlow.Table(new string[] {
                            "Label",
                            "X",
                            "Y",
                            "Z",
                            "SolarSystemID",
                            "ItemID",
                            "ID"});
                table59.AddRow(new string[] {
                            "safe: bookmark",
                            "16465",
                            "79798498",
                            "-47487676",
                            "1",
                            "-1",
                            "1"});
                table59.AddRow(new string[] {
                            "safe: station",
                            "-6546546",
                            "-2",
                            "1316354685",
                            "1",
                            "2",
                            "2"});
#line 185
testRunner.And("I have bookmarks", ((string)(null)), table59, "And ");
#line hidden
#line 189
testRunner.And("I am in solarsystem ID \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table60 = new TechTalk.SpecFlow.Table(new string[] {
                            "ID",
                            "Name",
                            "X",
                            "Y",
                            "Z",
                            "GroupID",
                            "Distance",
                            "IsTargetingMe"});
                table60.AddRow(new string[] {
                            "1",
                            "Dodixie IX",
                            "0",
                            "0",
                            "0",
                            "7",
                            "900000000000",
                            "false"});
                table60.AddRow(new string[] {
                            "2",
                            "Dodixie IX - 9 - Astral Mining Inc. Refinery",
                            "100",
                            "100",
                            "100",
                            "15",
                            "750987",
                            "false"});
#line 190
testRunner.And("I have entities", ((string)(null)), table60, "And ");
#line hidden
#line 194
testRunner.And("my home station is \'Dodixie IX - 9 - Astral Mining Inc. Refinery\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 195
testRunner.When("I get a safe spot", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 196
testRunner.Then("the the destination should be a bookmark destination matching bookmark ID \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Get safespot - No space safes available, should pick station safe")]
        public void GetSafespot_NoSpaceSafesAvailableShouldPickStationSafe()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get safespot - No space safes available, should pick station safe", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 198
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 199
testRunner.Given("I am in space", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 200
testRunner.And("my safe bookmark prefix is \'safe: \'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table61 = new TechTalk.SpecFlow.Table(new string[] {
                            "Label",
                            "X",
                            "Y",
                            "Z",
                            "SolarSystemID",
                            "ItemID",
                            "ID"});
                table61.AddRow(new string[] {
                            "safe: station",
                            "-6546546",
                            "-2",
                            "1316354685",
                            "1",
                            "200",
                            "2"});
#line 201
testRunner.And("I have bookmarks", ((string)(null)), table61, "And ");
#line hidden
#line 204
testRunner.And("I am in solarsystem ID \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table62 = new TechTalk.SpecFlow.Table(new string[] {
                            "ID",
                            "Name",
                            "X",
                            "Y",
                            "Z",
                            "GroupID",
                            "Distance",
                            "IsTargetingMe"});
                table62.AddRow(new string[] {
                            "1",
                            "Dodixie IX",
                            "0",
                            "0",
                            "0",
                            "7",
                            "900000000000",
                            "false"});
                table62.AddRow(new string[] {
                            "200",
                            "Dodixie IX - 9 - Astral Mining Inc. Refinery",
                            "100",
                            "100",
                            "100",
                            "15",
                            "750987",
                            "false"});
#line 205
testRunner.And("I have entities", ((string)(null)), table62, "And ");
#line hidden
#line 209
testRunner.And("my home station is \'Dodixie IX - 9 - Astral Mining Inc. Refinery\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 210
testRunner.When("I get a safe spot", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 211
testRunner.Then("the the destination should be an entity destination matching entity ID \'200\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Get safespot - No station safes available, should pick home station")]
        public void GetSafespot_NoStationSafesAvailableShouldPickHomeStation()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get safespot - No station safes available, should pick home station", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 213
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 214
testRunner.Given("I am in space", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 215
testRunner.And("my safe bookmark prefix is \'safe: \'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table63 = new TechTalk.SpecFlow.Table(new string[] {
                            "Label",
                            "X",
                            "Y",
                            "Z",
                            "SolarSystemID",
                            "ItemID",
                            "ID"});
#line 216
testRunner.And("I have bookmarks", ((string)(null)), table63, "And ");
#line hidden
                TechTalk.SpecFlow.Table table64 = new TechTalk.SpecFlow.Table(new string[] {
                            "ID",
                            "Name",
                            "X",
                            "Y",
                            "Z",
                            "GroupID",
                            "Distance",
                            "IsTargetingMe"});
                table64.AddRow(new string[] {
                            "1",
                            "Dodixie IX",
                            "0",
                            "0",
                            "0",
                            "7",
                            "900000000000",
                            "false"});
                table64.AddRow(new string[] {
                            "200",
                            "Dodixie IX - 9 - Astral Mining Inc. Refinery",
                            "100",
                            "100",
                            "100",
                            "15",
                            "750987",
                            "false"});
#line 218
testRunner.And("I have entities", ((string)(null)), table64, "And ");
#line hidden
#line 222
testRunner.And("my home station is \'Dodixie IX - 9 - Astral Mining Inc. Refinery\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 223
testRunner.When("I get a safe spot", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 224
testRunner.Then("the the destination should be an entity destination matching entity ID \'200\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 225
testRunner.And("we should dock at the destination", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 226
testRunner.And("the destination\'s distance should be \'200\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Get safespot - No home station available, should pick any station")]
        public void GetSafespot_NoHomeStationAvailableShouldPickAnyStation()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get safespot - No home station available, should pick any station", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 228
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 229
testRunner.Given("I am in space", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 230
testRunner.And("my safe bookmark prefix is \'safe: \'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table65 = new TechTalk.SpecFlow.Table(new string[] {
                            "Label",
                            "X",
                            "Y",
                            "Z",
                            "SolarSystemID",
                            "ItemID",
                            "ID"});
#line 231
testRunner.And("I have bookmarks", ((string)(null)), table65, "And ");
#line hidden
                TechTalk.SpecFlow.Table table66 = new TechTalk.SpecFlow.Table(new string[] {
                            "ID",
                            "Name",
                            "X",
                            "Y",
                            "Z",
                            "GroupID",
                            "Distance",
                            "IsTargetingMe"});
                table66.AddRow(new string[] {
                            "1",
                            "Dodixie IX",
                            "0",
                            "0",
                            "0",
                            "7",
                            "900000000000",
                            "false"});
                table66.AddRow(new string[] {
                            "200",
                            "Dodixie IX - 9 - Astral Mining Inc. Refinery",
                            "100",
                            "100",
                            "100",
                            "15",
                            "750987",
                            "false"});
#line 233
testRunner.And("I have entities", ((string)(null)), table66, "And ");
#line hidden
#line 237
testRunner.And("my home station is \'Dodixie IV - 20 - Blaze It Fgts\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 238
testRunner.When("I get a safe spot", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 239
testRunner.Then("the the destination should be an entity destination matching entity ID \'200\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 240
testRunner.And("we should dock at the destination", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 241
testRunner.And("the destination\'s distance should be \'200\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Get safespot - No station available, should pick a planet")]
        public void GetSafespot_NoStationAvailableShouldPickAPlanet()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get safespot - No station available, should pick a planet", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 243
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 244
testRunner.Given("I am in space", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 245
testRunner.And("my safe bookmark prefix is \'safe: \'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table67 = new TechTalk.SpecFlow.Table(new string[] {
                            "Label",
                            "X",
                            "Y",
                            "Z",
                            "SolarSystemID",
                            "ItemID",
                            "ID"});
#line 246
testRunner.And("I have bookmarks", ((string)(null)), table67, "And ");
#line hidden
                TechTalk.SpecFlow.Table table68 = new TechTalk.SpecFlow.Table(new string[] {
                            "ID",
                            "Name",
                            "X",
                            "Y",
                            "Z",
                            "GroupID",
                            "Distance",
                            "IsTargetingMe"});
                table68.AddRow(new string[] {
                            "100",
                            "Dodixie IX",
                            "0",
                            "0",
                            "0",
                            "7",
                            "900000000000",
                            "false"});
#line 248
testRunner.And("I have entities", ((string)(null)), table68, "And ");
#line hidden
#line 251
testRunner.When("I get a safe spot", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 252
testRunner.Then("the the destination should be an entity destination matching entity ID \'100\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 253
testRunner.And("the destination\'s distance should be \'100000000000\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Get safespot - Should not return any safespot we\'re already at - Space safe")]
        public void GetSafespot_ShouldNotReturnAnySafespotWereAlreadyAt_SpaceSafe()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get safespot - Should not return any safespot we\'re already at - Space safe", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 255
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 256
testRunner.Given("I am in space", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 257
testRunner.And("I am at point \'16465\',\'79798498\',\'-47487676\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 258
testRunner.And("my safe bookmark prefix is \'safe: \'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table69 = new TechTalk.SpecFlow.Table(new string[] {
                            "Label",
                            "X",
                            "Y",
                            "Z",
                            "SolarSystemID",
                            "ItemID",
                            "ID"});
                table69.AddRow(new string[] {
                            "safe: bookmark",
                            "16465",
                            "79798498",
                            "-47487676",
                            "1",
                            "-1",
                            "1"});
                table69.AddRow(new string[] {
                            "safe: bookmark 2",
                            "-6546546",
                            "-2",
                            "1316354685",
                            "1",
                            "-1",
                            "2"});
#line 259
testRunner.And("I have bookmarks", ((string)(null)), table69, "And ");
#line hidden
#line 263
testRunner.And("I am in solarsystem ID \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table70 = new TechTalk.SpecFlow.Table(new string[] {
                            "ID",
                            "Name",
                            "X",
                            "Y",
                            "Z",
                            "GroupID",
                            "Distance",
                            "IsTargetingMe"});
#line 264
testRunner.And("I have entities", ((string)(null)), table70, "And ");
#line hidden
#line 266
testRunner.When("I get a safe spot", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 267
testRunner.Then("the the destination should be a bookmark destination matching bookmark ID \'2\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Get safespot - Should not return any safespot we\'re already at - Planets")]
        public void GetSafespot_ShouldNotReturnAnySafespotWereAlreadyAt_Planets()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get safespot - Should not return any safespot we\'re already at - Planets", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 269
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 270
testRunner.Given("I am in space", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 271
testRunner.And("my safe bookmark prefix is \'safe: \'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table71 = new TechTalk.SpecFlow.Table(new string[] {
                            "Label",
                            "X",
                            "Y",
                            "Z",
                            "SolarSystemID",
                            "ItemID",
                            "ID"});
#line 272
testRunner.And("I have bookmarks", ((string)(null)), table71, "And ");
#line hidden
#line 274
testRunner.And("I am in solarsystem ID \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table72 = new TechTalk.SpecFlow.Table(new string[] {
                            "ID",
                            "Name",
                            "GroupID",
                            "Distance"});
                table72.AddRow(new string[] {
                            "100",
                            "Dodixie IX",
                            "7",
                            "40000000000"});
                table72.AddRow(new string[] {
                            "101",
                            "Dodixie X",
                            "7",
                            "871049581709827"});
#line 275
testRunner.And("I have entities", ((string)(null)), table72, "And ");
#line hidden
#line 279
testRunner.When("I get a safe spot", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 280
testRunner.Then("the the destination should be an entity destination matching entity ID \'101\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
